# Generated by Django 4.2.7 on 2023-11-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivedCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=150, verbose_name='Yetkazib beruvchi')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type_of_trade', models.CharField(choices=[('debt', 'Nasiya'), ('cash', 'Naqt')], max_length=50, verbose_name='Savdo Turi')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mijoz')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type_of_trade', models.CharField(choices=[('debt', 'Nasiya'), ('cash', 'Naqt')], max_length=50, verbose_name='Savdo Turi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('actual_price', models.PositiveBigIntegerField(help_text='Mahsulotni olib kelingan narxi')),
                ('selling_price', models.PositiveBigIntegerField(help_text='Mahsulotni sotilish narxi')),
                ('wholesale_price', models.PositiveBigIntegerField(help_text='Mahsulotni chakana narxi')),
                ('type_of_measurement', models.CharField(choices=[('kg', 'Kilogram'), ('metr', 'Metr'), ('pc', 'Dona'), ('litr', 'Litr')], max_length=5)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='SelledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('type_of_price', models.CharField(choices=[('selling', 'Sotilish Narxi'), ('wholesale', 'Optom Narx'), ('actual', 'Haqiqiy Narxi')], max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
