# Generated by Django 4.2.7 on 2023-11-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivedcargo',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='selledproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='selledproduct',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='selledproduct',
            name='type_of_price',
            field=models.CharField(choices=[('selling', 'Sotilish Narxi'), ('wholesale', 'Optom Narx'), ('actual', 'Haqiqiy Narxi')], max_length=25, verbose_name='Narx turi'),
        ),
    ]
