# Generated by Django 4.2.7 on 2023-11-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtarrivedcargo',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='debtcustomer',
            options={'ordering': ['-created']},
        ),
    ]
